version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_prueba
      - DB_USERNAME=root
      - DB_PASSWORD=Salamanca06*
    volumes:
      - ./:/var/www
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Salamanca06*
      MYSQL_DATABASE: test_prueba
    volumes:
      - dbdata_test:/var/lib/mysql

volumes:
  dbdata_test: