services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=prueba
      - DB_USERNAME=root
      - DB_PASSWORD=Salamanca06*
    volumes:
      - ./:/var/www
    networks:
      - laravel_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Salamanca06*
      - MYSQL_DATABASE=prueba
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_net
    depends_on:
      - app

networks:
  laravel_net:
    driver: bridge

volumes:
  dbdata: